apiVersion: v1
kind: Secret
metadata:
  name: streamflix-secrets
  namespace: streamflix
type: Opaque
stringData:
  POSTGRES_USER: streamflix_user
  POSTGRES_PASSWORD: streamflix_pass
  POSTGRES_DB: userdb
  mongo_initdb_root_username: mongo_root
  mongo_initdb_root_password: mongo_pass
  TMDB_API_KEY: "4f038172f472098103c497d8e0301043"
